# Generated by Django 3.0.6 on 2020-11-12 16:21

import banners.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20201107_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone')),
                ('status', models.IntegerField(choices=[(1, 'QUEUE'), (2, 'PROCESSING'), (3, 'PROCESSED')], default=banners.models.QueueItemStatus['QUEUE'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Banner')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
