# Generated by Django 3.0.6 on 2020-11-22 12:39

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_queueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='banners.Banner'),
        ),
    ]
