# Generated by Django 3.0.6 on 2020-11-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_queueitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='banners.Banner'),
        ),
    ]
