# Generated by Django 3.0.6 on 2021-02-13 18:43

import banners.models.queue_item
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20201206_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=1, enum=banners.models.queue_item.QueueItemStatus),
        ),
    ]
