# Generated by Django 3.0.6 on 2021-02-13 19:16

import banners.models.queue_item
import django.core.validators
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20210213_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='source',
            field=django_enumfield.db.fields.EnumField(default=1, enum=banners.models.queue_item.QueueItemSource),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='telegram_chat_id',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
