# Generated by Django 3.0.6 on 2021-02-14 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_auto_20210213_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Banner')),
            ],
        ),
    ]
