# Generated by Django 3.2.6 on 2021-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_auto_20210221_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
