# Generated by Django 3.1.12 on 2021-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_queueitem_past'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueitem',
            options={'base_manager_name': 'objects', 'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='queueitem',
            name='processing_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='processing_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
