# Generated by Django 3.1.12 on 2021-09-14 21:22

import banners.models.queue_item
import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0013_queueitem_waiting_time_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='processing_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='status',
            field=django_fsm.FSMIntegerField(default=banners.models.queue_item.QueueItemStatus(1), verbose_name=banners.models.queue_item.QueueItemStatus),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='waiting_time_estimation',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
